services:
  database-svc:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00tSecret
      MYSQL_DATABASE: wpsite
      MYSQL_USER: blog_admin
      MYSQL_PASSWORD: blogPass2025
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  wp-demo:
    depends_on:
      database-svc:
        condition: service_healthy
    image: wordpress:latest
    ports:
      - "8005:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database-svc:3306
      WORDPRESS_DB_USER: blog_admin
      WORDPRESS_DB_PASSWORD: blogPass2025
      WORDPRESS_DB_NAME: wpsite

volumes:
  mysql_data:
